version: '2'
services:
  web:
    build: web
    ports:
      - "8000:8000" 
    volumes_from:
      - data
    depends_on:
      - redis
      - db
      - rabbit
  redis:
    image: redis
  db:
    image: postgres
  rabbit:
    hostname: rabbit
    image: rabbitmq
  data:
    image: ubuntu
    restart: always
    volumes:
      - ./web/data:/bk20/data
      - ./web/logs:/bk20/logs
    command: "true"
